workflows:
  android-workflow:
    name: Android Build 21
    max_build_duration: 60
    instance_type: linux
    environment:
      groups:
        - nexus_credentials # Se usares, senão podes apagar esta linha e a de cima
      node: v22.12.0
      java: 21
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Vite Build
        script: npm run build
      - name: Capacitor Sync
        script: npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          # O segredo: Não usar caches antigos de builds que falharam com Java 17
          ./gradlew assembleDebug --no-daemon --no-build-cache --stacktrace
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - joaosilvabastos@gmail.com
